//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NofeshloadTest
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using Microsoft.VisualStudio.TestTools.WebTesting;
    using Microsoft.VisualStudio.TestTools.WebTesting.Rules;


    [DeploymentItem("nofeshloadtest\\dataNofashim.txt")]
    [DataSource("dataNofesh", "Microsoft.VisualStudio.TestTools.DataSource.CSV", "|DataDirectory|\\dataNofashim.txt", Microsoft.VisualStudio.TestTools.WebTesting.DataBindingAccessMethod.Sequential, Microsoft.VisualStudio.TestTools.WebTesting.DataBindingSelectColumns.SelectOnlyBoundColumns, "dataNofashim#txt")]
    public class SaveNofeshTashlumimProdCoded : WebTest
    {

        public SaveNofeshTashlumimProdCoded()
        {
            this.PreAuthenticate = true;
            this.Proxy = "default";
        }

        public override IEnumerator<WebTestRequest> GetRequestEnumerator()
        {
            // Initialize validation rules that apply to all requests in the WebTest
            if ((this.Context.ValidationLevel >= Microsoft.VisualStudio.TestTools.WebTesting.ValidationLevel.Low))
            {
                ValidateResponseUrl validationRule1 = new ValidateResponseUrl();
                this.ValidateResponse += new EventHandler<ValidationEventArgs>(validationRule1.Validate);
            }
            if ((this.Context.ValidationLevel >= Microsoft.VisualStudio.TestTools.WebTesting.ValidationLevel.Low))
            {
                ValidationRuleResponseTimeGoal validationRule2 = new ValidationRuleResponseTimeGoal();
                validationRule2.Tolerance = 0D;
                this.ValidateResponseOnPageComplete += new EventHandler<ValidationEventArgs>(validationRule2.Validate);
            }

            WebTestRequest request1 = new WebTestRequest("https://pre-www5.tel-aviv.gov.il/tlvservices/tlvirgunovdim/api/Nofesh/SaveNofeshTashl" +
                    "umim");
            request1.Method = "POST";
            request1.Headers.Add(new WebTestRequestHeader("Pragma", "no-cache"));
            request1.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/plain, */*"));
            request1.Headers.Add(new WebTestRequestHeader("Referer", "https://pre-www5.tel-aviv.gov.il/Tlvirgunovdim/"));
            request1.Headers.Add(new WebTestRequestHeader("Authorization", ("Bearer " + this.Context["access_token"].ToString())));
            StringHttpBody request1Body = new StringHttpBody();
            request1Body.ContentType = "application/json";
            request1Body.InsertByteOrderMark = false;
            var tz = this.Context["dataNofesh.dataNofashim#txt.user"].ToString();
            request1Body.BodyString = "{\"nofesh_id\":37,\"ms_zehut_mazmin\":300020674,\"tashlumim\":[{\"ms_zehut_meshalem\":300" +
                "020674,\"ofen_tashlum\":\"1\",\"ms_tashlumim\":1,\"schum_tashlum\":3730,\"teur_tashlum\":\"" +
                "\"}]}";
            request1Body.BodyString = request1Body.BodyString.Replace("300020674", tz);
            request1.Body = request1Body;
            yield return request1;
            request1 = null;
        }
    }
}
