//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NofeshloadTest
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using Microsoft.VisualStudio.TestTools.WebTesting;
    using Microsoft.VisualStudio.TestTools.WebTesting.Rules;


    [DeploymentItem("nofeshloadtest\\dataNofashim.txt")]
    [DataSource("dataNofesh", "Microsoft.VisualStudio.TestTools.DataSource.CSV", "|DataDirectory|\\dataNofashim.txt", Microsoft.VisualStudio.TestTools.WebTesting.DataBindingAccessMethod.Sequential, Microsoft.VisualStudio.TestTools.WebTesting.DataBindingSelectColumns.SelectOnlyBoundColumns, "dataNofashim#txt")]
    public class SaveNofeshNirshamimCoded : WebTest
    {

        public SaveNofeshNirshamimCoded()
        {
            this.Context.Add("Server", "https://www5.tel-aviv.gov.il");
            this.PreAuthenticate = true;
            this.Proxy = "default";
        }

        public override IEnumerator<WebTestRequest> GetRequestEnumerator()
        {
            // Initialize validation rules that apply to all requests in the WebTest
            if ((this.Context.ValidationLevel >= Microsoft.VisualStudio.TestTools.WebTesting.ValidationLevel.Low))
            {
                ValidateResponseUrl validationRule1 = new ValidateResponseUrl();
                this.ValidateResponse += new EventHandler<ValidationEventArgs>(validationRule1.Validate);
            }
            if ((this.Context.ValidationLevel >= Microsoft.VisualStudio.TestTools.WebTesting.ValidationLevel.Low))
            {
                ValidationRuleResponseTimeGoal validationRule2 = new ValidationRuleResponseTimeGoal();
                validationRule2.Tolerance = 0D;
                this.ValidateResponseOnPageComplete += new EventHandler<ValidationEventArgs>(validationRule2.Validate);
            }

            WebTestRequest request1 = new WebTestRequest("https://www5.tel-aviv.gov.il/tlvservices/tlvirgunovdim/api/Nofesh/SaveNofeshNirsh" +
                    "amim");
            request1.Method = "POST";
            request1.Headers.Add(new WebTestRequestHeader("Pragma", "no-cache"));
            request1.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/plain, */*"));
            request1.Headers.Add(new WebTestRequestHeader("Referer", "https://www5.tel-aviv.gov.il/Tlvirgunovdim/"));
            request1.Headers.Add(new WebTestRequestHeader("Authorization", ("Bearer " + this.Context["access_token"].ToString())));
            StringHttpBody request1Body = new StringHttpBody();
            request1Body.ContentType = "application/json";
            request1Body.InsertByteOrderMark = false;
            var tz = this.Context["dataNofesh.dataNofashim#txt.user"].ToString();

            var id_nofesh = this.Context["dataNofesh.dataNofashim#txt.id_nofesh"].ToString();
            request1Body.BodyString = @"{""id_nofesh"":""37"",""nirshamim"":[{""ms_zehut"":300020674,""shem_prati"":""הילה"",""shem_mishpacha"":""צפירה"",""ms_darkon"":""546465487913241"",""tr_tokef_darkon"":""2020-09-04T00:00:00.000Z"",""shem_prati_loazi"":""Kuku"",""shem_mishpacha_loazi"":""Rico"",""phone"":""0522340406"",""email"":""hilla1986@gmail.com"",""llo_nitsul_zakaut"":0}]}";
            request1Body.BodyString = request1Body.BodyString.Replace("300020674", tz);
            request1Body.BodyString = request1Body.BodyString.Replace("37", id_nofesh);
            request1.Body = request1Body;
            yield return request1;
            request1 = null;
        }
    }
}
